
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build images
        run: |
          docker build -t ${{ secrets.REGISTRY_USER }}/portfolio:{{github.run_number}} .
          docker build -t ${{ secrets.REGISTRY_USER }}/portfolio .

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }}
          docker push ${{ secrets.REGISTRY_USER }}/portfolio:{{github.run_number}}
          docker push ${{ secrets.REGISTRY_USER }}/portfolio
